### MangoHud overlay - toggle with Right-Shift + F12
toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2

## What to show
fps
frametime=1
frame_timing=1
gpu_stats
gpu_temp
cpu_stats
cpu_temp
ram
vram
resolution
refresh_rate

## Appearance
position=top-left
font_size=26
background_alpha=0.4
round_corners=8
